Repository wecode-bootcamp-korea/31-1st-Wesop-frontend, pull requests merged in 2022-04, with the labels that each got.

#5 [31기 전지현] 로그인 모달창 레이아웃, 백앤드와 통신 ,유효성검사 구현
  src/components/Login/DATA/LOGIN_DATA.js
  src/components/Login/DATA/LOGIN_MESSAGE.js
  src/components/Login/LoginBackMiniBtn.js
  src/components/Login/LoginBackMiniBtn.scss
  src/components/Login/LoginCard.js
  src/components/Login/LoginCard.scss
  src/components/Login/LoginCloseMainBtn.js
  src/components/Login/LoginCloseMainBtn.scss
  src/components/Login/LoginCloseMiniBtn.js
  src/components/Login/LoginCloseMiniBtn.scss
  src/components/Login/LoginInput.js
  src/components/Login/LoginInput.scss
  src/components/Login/LoginMessage.js
  src/components/Login/LoginMessage.scss
  src/components/Login/LoginSubmitBtn.js
  src/components/Login/LoginSubmitBtn.scss
  src/components/UI/ModalOverLay.js
  src/components/UI/ModalOverLay.scss
  src/config/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm.js
  src/pages/Login/LoginForm.scss
Labels: Status: Accepted

#10 [31기 전지현] Nav 컴포넌트에 Login 컴포넌트 부착
  src/components/Nav/CategoryElement.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/userCategoryData.js
  src/components/UI/ModalOverLay.js
  src/config/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm.js
  src/pages/ProductList/ProductList.js
Labels: Status: Accepted

#9 [31기 김민주] 쿼리파라미터에 따른 카테고리별 페이지 이동 및 조건부 렌더링(전체상품or카테고리페이지)
  public/data/all-product.json
  public/data/category.json
  public/data/category_products.json
  src/Router.js
  src/components/Login/DATA/LOGIN_DATA.js
  src/components/Login/DATA/LOGIN_MESSAGE.js
  src/components/Login/LoginBackMiniBtn.js
  src/components/Login/LoginBackMiniBtn.scss
  src/components/Login/LoginCard.js
  src/components/Login/LoginCard.scss
  src/components/Login/LoginCloseMainBtn.js
  src/components/Login/LoginCloseMainBtn.scss
  src/components/Login/LoginCloseMiniBtn.js
  src/components/Login/LoginCloseMiniBtn.scss
  src/components/Login/LoginInput.js
  src/components/Login/LoginInput.scss
  src/components/Login/LoginMessage.js
  src/components/Login/LoginMessage.scss
  src/components/Login/LoginSubmitBtn.js
  src/components/Login/LoginSubmitBtn.scss
  src/components/ModalOverLay/ModalOverLay.scss
  src/config/config.js
  src/pages/Login/Login.js
  src/pages/Login/LoginForm.scss
  src/pages/ProductList/Category/Category.js
  src/pages/ProductList/Category/Product/Product.js
  src/pages/ProductList/Category/Product/ProductSizePrice/ProductSizePrice.js
  src/pages/ProductList/Category/Product/ProductSizePrice/ProductSizePrice.scss
  src/pages/ProductList/CategoryList/CategoryList.js
  src/pages/ProductList/CategoryList/CategoryList.scss
  src/pages/ProductList/CategoryList/CategoryProduct/CategoryProduct.js
  src/pages/ProductList/CategoryList/CategoryProduct/CategoryProduct.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListLayout/ProductListLayout.js
  src/pages/ProductList/ProductListLayout/ProductListLayout.scss
Labels: Status: 수정 요청

#11 [31기 전지현] Cart 모달창 레이아웃, 펑션
  src/components/Nav/CategoryElement.js
  src/components/Nav/Nav.js
  src/components/UI/ModalOverLay.js
  src/config/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItemList.js
  src/pages/Cart/CartItemList.scss
  src/pages/Login/Login.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailSection/ProductDetailSection.js
Labels: Status: Accepted

#14 [31기 김민주] Fix : Footer 삭제, 카테고리명 오류 수정, location.search 뒤 숫자 부분 일부 수정
  src/config/config.js
  src/pages/ProductList/ProductList.css
  src/pages/ProductList/ProductList.css.map
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductListLayout/ProductListLayout.js
Labels: Status: Accepted

#13 [31기 최희동] Nav바에 메뉴, 검색기능 구현 완료
  public/images/common/MenuImage.jpg
  src/components/Nav/CategoryElement.js
  src/components/Nav/CategoryElement.scss
  src/components/Nav/Menu/CATEGORY_LIST.js
  src/components/Nav/Menu/MenuCategory.js
  src/components/Nav/Menu/MenuCategory.scss
  src/components/Nav/Menu/NavMenu.js
  src/components/Nav/Menu/NavMenu.scss
  src/components/Nav/Menu/SKIN_TYPE_LIST.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Search/Search.js
  src/components/Nav/Search/Search.scss
  src/components/Nav/Search/SearchImage.js
  src/components/Nav/Search/SearchImage.scss
  src/components/Nav/Search/SearchList.js
  src/components/Nav/Search/SearchList.scss
  src/components/Nav/navCategoryData.js
  src/styles/variables.scss
Labels: Status: Accepted

#16 [31기 전지현] 1차 프로젝트 발표 통합버전
  src/Router.js
  src/components/Login/DATA/LOGIN_DATA.js
  src/components/Login/DATA/LOGIN_MESSAGE.js
  src/components/Login/LoginBackMiniBtn.js
  src/components/Login/LoginBackMiniBtn.scss
  src/components/Login/LoginCard.js
  src/components/Login/LoginCard.scss
  src/components/Login/LoginCloseMainBtn.js
  src/components/Login/LoginCloseMainBtn.scss
  src/components/Login/LoginCloseMiniBtn.js
  src/components/Login/LoginCloseMiniBtn.scss
  src/components/Login/LoginInput.js
  src/components/Login/LoginInput.scss
  src/components/Login/LoginMessage.js
  src/components/Login/LoginMessage.scss
  src/components/Login/LoginSubmitBtn.js
  src/components/Login/LoginSubmitBtn.scss
  src/components/ModalOverLay/ModalOverLay.scss
  src/components/Nav/Menu/MenuCategory.js
  src/components/Nav/Menu/MenuCategory.scss
  src/components/Nav/Nav.scss
  src/components/Nav/Search/Search.js
  src/config/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartItemList.js
  src/pages/Cart/CartItemList.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginForm.js
  src/pages/Login/LoginForm.scss
  src/pages/Main/Main.js
  src/pages/Main/MainCarousel.js
  src/pages/Main/MainCarousel.scss
  src/pages/Main/MainVideo.js
  src/pages/Main/Selection.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailAside/ProductDetailAside.js
  src/pages/ProductDetail/ProductDetailSection/ProductDetailSection.js
  src/pages/ProductList/Category/Category.js
  src/pages/ProductList/Category/Product/Product.js
  src/pages/ProductList/CategoryList/CategoryProduct/CategoryProduct.js
  src/pages/ProductList/FilterOpen/FilterColumn/FilterColumnContent/FilterColumnContent.js
  src/pages/ProductList/ProductList.css
  src/pages/ProductList/ProductList.css.map
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청
